### PR TITLE
Prettier settings for vscode

### PR DESCRIPTION
**Pull request by ross-p-smith**
These are the settings that are used in the main CCF repo to keep them inline

- Also added the GitHub plugin seeing as we do most of the work in GH

Relates to #111

### CODE REVIEW

**Comment by macromania** [comment]
I think there are more pieces to add in order to make formatter work the same way for everyone 😅
https://github.com/macromania/typescript-starter/blob/main/docs/project-setup.md#setup-eslint-and-prettier

**Comment by ross-p-smith** [comment]
Agreed, that issue is assigned to you. I was doing these pieces as they effect other file types as well as TypeScript.

**Review by macromania — APPROVED** [review]
we can pull this in and improve it with #111 later on.

**Review by Aymalla — APPROVED** [review]
LGTM

**Pull request merged**
