### PR TITLE
Update dev container to 3.0.1

### PR DESCRIPTION
**Pull request by achamayou**

### CODE REVIEW

**Comment by ross-p-smith** [comment]
If this has a new sandbox.sh bundled up with it, then we can remove the extra line in the postcreatecommand (in this file)

**Comment by achamayou** [comment]
@ross-p-smith I'm not sure what you mean by new? It's got the sandbox at that time?

I think the reason this breaks is because the install prefix is now split, like the packages, and so the path should be `/opt/ccf_virtual/...` instead of `/opt/ccf/...`.

**Comment by ross-p-smith** [comment]
> @ross-p-smith I'm not sure what you mean by new? It's got the sandbox at that time?
> 
> I think the reason this breaks is because the install prefix is now split, like the packages, and so the path should be `/opt/ccf_virtual/...` instead of `/opt/ccf/...`.

I put in a quick hack to copy sandbox.sh from this repo over the top of /opt/ccf/bin/sandbox.sh until we upgraded the devcontainer. If we are now upgrading the dev container, we don't need to copy that file in the postcreatecommand as it already exists in the right place(?!?).

**Comment by achamayou** [comment]
@ross-p-smith oh I see, sorry, yes no this is definitely the up to date script in 3.0.1.

**Comment by ross-p-smith** [comment]
This
```
"postCreateCommand": "npm install --prefix=banking-app && npm install --prefix=auditable-logging-app && cp sandbox.sh /opt/ccf/bin/sandbox.sh",
```
becomes
```
"postCreateCommand": "npm install --prefix=banking-app && npm install --prefix=auditable-logging-app",
```

**Comment by achamayou** [comment]
@ross-p-smith unfortunately it's out of range for the UI suggestion, but I think a number of other paths need to be updated, so let me do that too.

**Comment by ross-p-smith** [comment]
We had this on our backlog - so just linking that this will Fix #60

**Comment by ross-p-smith** [comment]
@achamayou - I pulled your branch and I can reproduce this same problem by running 

`/workspaces/ccf-app-samples/banking-app# make test-docker-virtual`

I can look into this as a separate bug as it's a docker issue and not the new image that you have added. If you edit https://github.com/microsoft/ccf-app-samples/blob/7565b673cf5822c6379c3493496edc6e1b9a9462/.github/workflows/ci.yml#L27

And remove `make test-docker-virtual` for now as everything else works

**Review by ross-p-smith — APPROVED** [review]
Approved if we remove `make test-docker-virtual` temporarily from CI

**Review by takuro-sato — APPROVED** [review]

**Pull request merged**
